version: "3.8"
volumes:
  db-store:
  php-fpm-socket:
services:
  app:
    build: ./docker/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - .:/work/backend

  web:
    build: ./docker/nginx
    ports:
      - 81:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - .:/work/backend

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3307:3306
